#!/usr/bin/python3
# -*- coding:utf-8 -*-

import unittest
from UnitTest_1.test_function import TestFunc
from HTMLTestRunner import HTMLTestRunner
# 在Python3中已经没有 StringIO，所以引用的时候要注意
from io import StringIO

if __name__ == "__main__":
    suite = unittest.TestSuite()
    # 定义list，按照list里的顺序执行测试用例
    tests = [TestFunc("test_add"),TestFunc("test_minus"),TestFunc("test_multi"),TestFunc("test_divide")]
    suite.addTests(tests)
    '''
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)
    '''
    
    # 生成.txt的测试报告（控制台的输出写入到文件中）
    '''
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestFunc))
    with open('UnittestTextReport.txt','a') as f:
        runner = unittest.TextTestRunner(stream=f,verbosity=2)
        runner.run(suite)
    '''

    # 生成HTML格式的具体测试报告
    with open('HtmlReport.html','wb') as f:  # 在python3，要写成'wb' or 'wr'
        runner = HTMLTestRunner(stream=f,title='function test report',description='generated by  HTMLTestRunner',verbosity=2)
        runner.run(suite)